### ISSUE TITLE
GetTagValue() 함수가 웹 랜더러에서 동작을 수행하지 않음.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#1]
@lwh4525 다음과 같이 enuSpace에서 코드를 추가하였을 경우, enuSpace에서는 정상적인 동작을 수행하나, 웹 랜더러에서 적용이 안되는 현상이 있음.
function _ontaskview()
{   
   var i;
   var j;
   var variable;
   for (i = 0; i < 16; i++) 
   { 
      for (j = 0; j < 16; j++) 
      { 
         data[i][j] = GetTagValue("@CORE.display[" + i + "][" + j + "]");
      }
   } 
}

**Comment by lwh4525** [comment]
GetTagValue의 문제가 아닌 스크립트를 변환하는 과정에서 data[i][j]를 변환하지 못하여 생긴 현상 입니다.
이제는 배열 변수도 'objID'.data[i][j] 로 변환 하게 만들어서 해결되었습니다.
