### ISSUE TITLE
enuSpace에서 기존에 생성된 DB변수 값을 선택후 더블클릭하면 DB변수 값 수정가능하게 변경해야됩니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#10]
![db](https://user-images.githubusercontent.com/38027211/38410447-8d34d706-39bf-11e8-9fa3-9f44352bdb85.png)

**Comment by khm34software** [comment]
[02c42a8](http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293)

**Comment by BrightJoy** [comment]
![image](https://user-images.githubusercontent.com/29910594/38543888-cf909dc8-3ce0-11e8-8533-ba8504908370.png)

데이터베이스 변경 버튼 추가 및 리스트컨트롤을 더블클릭하였을 경우 변경 다이얼로그 함수를 통하여 변경할 수 있도록 조치하였습니다. 확인 부탁합니다.

**Comment by khm34software** [comment]
DB 변경버튼과 더블클릭 후 값은 제대로 변경됩니다. 아래와 같은 에러가 확인 되었습니다.

DB변수 test.input3의 변수타입 double을 int로만 변경 후 초기값은 0.000000에서 변경하지 않고 실행하면 게이지의 값이 쓰레기값으로 지정되어 실행되지 않고 값을 0으로 초기화 후 실행하면 정상 실행됨.
int 타입의 초기값을 소수점을 입력하지 못하게 변경하거나 소수점을 입력하면 반올림 또는 반내림하여 적용되게 변경요청
![db double int 0 000000 0](https://user-images.githubusercontent.com/38027211/38548456-d0f7056a-3cec-11e8-8366-4120fc13e93a.png)

**Comment by BrightJoy** [comment]
변수의 형에 대하여 값을 지시하도록 수정하였습니다. 또한, 데이터베이스 변경시 객체의 SetAttribute의 변수 할당정보에 대하여 재검토후 업데이트 하도록 수정하였습니다.
@khm34software 검토바랍니다.

**Comment by khm34software** [comment]
DB변수 Type을 선택시 해당 변수 Type에 맞게 Init value 값의 초기값을 자동생성하게 하고, 사용자가 초기값을 입력 시 변수 Type별로 자동 보정 기능이 필요합니다. 
(ex. bool형 일경우 초기값이 true 또는 false로 두가지만 지정되게 적용하거나 그 외의 값 0일경우에만 false로 하고 절대값 기준 0이아닌 정수값인 +값, -값 입력시 true로 적용하고 문자입력시에도 true로 적용되게 변경요청)
![default](https://user-images.githubusercontent.com/38027211/38592194-9cc0034e-3d75-11e8-890e-6a3d4b26174c.png)
기존의 int형 변수를 string형으로 변경 후 초기값에 문자를 입력후 적용하면 아래와 같은 에러가 발생합니다.
![default](https://user-images.githubusercontent.com/38027211/38592217-d0502d06-3d75-11e8-82f4-0f7b983f405d.png)
![string 1](https://user-images.githubusercontent.com/38027211/38592248-007050b0-3d76-11e8-9bd2-3fcb8ec3af68.png)

**Comment by BrightJoy** [comment]
string 데이터의 변수의 메모리 제거시 현재의 타입정보를 확인하여 제거를 수행하여, 메모리 누수 에러 발생에 대하여 패치하였습니다.
또한, 타입콤보박스 변경에 따라서 초기값을 설정하는 로직을 추가하였습니다.

**Comment by khm34software** [comment]
정상 동작 확인하였습니다.
