### ISSUE TITLE
enuSpace의 Libray-Hmi-*****.svg 컴포넌트 생성시 객체의 우선순위 선정기능이 필요합니다. (클릭한 객체가 위로 오게끔 변경)

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#11]
먼저 추가한 객체가 뒤로 가기때문에 컴포넌트 생성시 불편합니다.

![default](https://user-images.githubusercontent.com/38027211/38410825-94f3fd40-39c0-11e8-98d3-2d24f168bb12.png)

**Comment by khm34software** [comment]
드로잉 객체의 순서를 의미합니다.
드로잉 객체의 순서가 먼저 생성된 순서대로 뒤에 배치되는데 객체 생성 완료 후 선택된 객체가 앞으로 오게끔하여 객체의 우선순위를 자동으로 변경되게하여 완성된 객체의 모양을 사용자가 원하는대로 지정되게 변경되었으면 합니다.

**Comment by BrightJoy** [comment]
마우스 클릭에의하여 선택객체가 최상위 순서로 변경된다면, 발생되는 불편사항이 있을것 같습니다. 객체의 순서와 스크립트 처리간에 정의된 경우에 순서를 바꾸면 안되는 상황이 있을것으로 보이며 객체의 순서는 사용자가 지정하는 bring to front, bring to back기능을 이용하면 될것 같습니다.

**Comment by khm34software** [comment]
bring to front, bring to back 기능으로 충분할것으로 보입니다.
하지만 위의 기능에 의한 객체의 순서를 바꿀때 스크립트 처리간 정의된 경우에 발생할수 있는 요소는 처리되었다고 판단됩니다. 자동순서기능을 적용하는데에도 무리가 없어 보입니다.
담당자분의 의견대로 기존의 기능을 유지하는것으로 완료하겠습니다.
