### ISSUE TITLE
enuSpace 설치 된 상태에서 enuSpace 재설치 후 실행 시 MainFrame Initial Failed 에러가 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#12]
리본폰트콤보박스부분에서 에러발생합니다.

![default](https://user-images.githubusercontent.com/38027211/38411262-a973ff94-39c1-11e8-8abc-a3263b0f4603.png)

**Comment by BrightJoy** [comment]
@lwh4525 위와 같은 증상이 나타나는 원인에 대하여 답해줄수 있나요? 해결방법은 무엇이 있을까요? 답변가능하면 답변 부탁드립니다.

**Comment by lwh4525** [comment]
@khm34software @BrightJoy 버그를 찾고 있습니다.

**Comment by BrightJoy** [comment]
아래 두가지를 확인해 보는건 어떨까요?

- 폰트 이름에 대한 드로잉 설정을 false로 지정하였을 경우 동일 현상이 나타나느지?
- 해결이 되는 재배포 패키지 버젼이 무엇인지?

**Comment by khm34software** [comment]
재 설치 시 인스톨쉴드에서 repair, remove 기능이 있는지 궁금합니다.
제어판-프로그램삭제에서 목록에서 검색후 삭제시 모든 레지스트리 파일이 삭제되는지도 궁금합니다.

현재 제 컴퓨터에 중복 설치 후 복구가 안되면 업무진행이 안될것 같아서 질문 남깁니다.

**Comment by lwh4525** [comment]
@khm34software 제어판에서 작업시 변경, 복구 기능이 있습니다. 
1) (win10 이전)제어판 -> 프로그램 및 기능 -> 설치된 enuspace에서 오른쪽 클릭
2) (win10) 제어판 -> 앱 -> 설치된 enuspace를 왼쪽 클릭(메뉴는 수정, 삭제 밖에 없음)

**Comment by lwh4525** [comment]
@khm34software @BrightJoy 재배포패키지의 버전문제 인것으로 확인되었습니다. 재배포 패키지의 버전이  14.0.24215 버전 보다 낮으면 메인프레임 에러가 나타납니다. 따라서 14.0.24215 버전보다 높은 버전을 설치하여 에러를 나지 않게 하면 됩니다. enuspace의 설치파일에 포함 시킬 재배포 패키지의 버전을 14.0.24215 버전으로 변경하겠습니다.
