### ISSUE TITLE
enuSpace의 리본폰트에서 폰트의 값을 직접 입력 가능하게 변경해야 합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#13]
아래 그림의 빨간색 네모칸안에 폰트의 값을 직접 입력 가능하게 변경해야 됩니다.
![default](https://user-images.githubusercontent.com/38027211/38411764-c9464592-39c2-11e8-89c2-c80c7a429361.png)

**Comment by lwh4525** [comment]
fontsize 콤보박스를 edit 가능하게 변경 하였습니다. 업데이트 하시고 확인하시기 바랍니다.

**Comment by khm34software** [comment]
Library-Hmi-automaatic.svg-pump에서 Text와 Edit Box 생성 후 각각의 객체 삭제시 아래와 같은 에러가 발생합니다. (폰트의 값을 임의의 값으로 수정하여 적용한 후에도 두개의 객체 삭제시 같은 에러가 발생합니다.)
![text_editbox_error](https://user-images.githubusercontent.com/38027211/38592900-a64ae9b6-3d79-11e8-867e-2e25de291c0e.png)
![text_editbox_error1](https://user-images.githubusercontent.com/38027211/38592935-d32af0d4-3d79-11e8-82b8-f97f2c3d5e91.png)

**Comment by khm34software** [comment]
정상 독작합니다.

**Comment by BrightJoy** [comment]
@lwh4525 차트에서 사용되는 글꼴, 폰트 사이즈, 폰트 스타일 정보등이 연결되면 사용자가에 추가 편의를 제공할 수 있을것 같습니다. 현재는 차트의 우측 속성정보에 의해서 전달되고 있으나, 상단의 Font 판넬에 대해서도 확장적용하면 좋을것 같습니다. 확장방안 검토 부탁합니다.

**Comment by khm34software** [comment]
Chart 와 Contour Chart 의 크기가 변경되에 따라 폰트의 크기가 자동 변경되거나 폰트 스타일 정보등이 연결되게 되면 사용자의 편의성이 제공될것 같습니다.
![chart_contour chart](https://user-images.githubusercontent.com/38027211/38602498-dda6aed2-3da5-11e8-8fd4-997b277215a1.png)

**Comment by lwh4525** [comment]
@khm34software 차트의 크기에 따라 폰트 크기를 조정하는 작업은 많은 조건을 필요로 합니다. 현재 사용자가 모든것을 조절할 수 있게 만든대신에 그러한 편의 기능은 들어가 있지 않습니다. 차트의 크기가 일정 수준일 때 어느정도의 폰트 크기이면 보기 좋을지 알려주시면 조건을 적용 하여 차트에 반영 하겠습니다.

**Comment by khm34software** [comment]
리본폰트의 폰트값을 연동하여 적용시키는게 좋을것 같습니다.

**Comment by khm34software** [comment]
차트 객체를 생성했을때 처음 생성되는 렉트의 사이즈값과 폰트의 크기 값을 처음 값으로 가지고있고 차트의 렉트를 늘릴 경우 렉트의 사이즈값을 확인하여 폰트의 크기 값을 넣어주는 비례적용을 하면 될 것 같습니다.
처음 챠트의 렉트:처음 폰트 사이즈 = 변경된 차트의 렉트 : X (변경될 폰트 사이즈)
x : y = x1 : y1

Chart의 경우 고정크기로 처음 생성되지만 Contour Chart는 고정크기로 생성되지 않아서 적용하기 힘들수도 있습니다.

최선의 방안은 리본포트의 폰트값을 연동하여 적용시키는게 제일 좋을것 같습니다.
