### ISSUE TITLE
enuSpace의 Project Explorer에서 F2 또는 마우스 우클릭으로 이름을 변경할 수 있게 해야 됩니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#14]
![f2_](https://user-images.githubusercontent.com/38027211/38412313-04d8b97c-39c4-11e8-9e5e-b05c3f9fb363.png)

**Comment by BrightJoy** [comment]
프로젝트 익스플로어에서 마우스 더블클릭을 이용하여 해당 이름을 변경하는 기능을 추가하였습니다.

변경가능 목록
- 글로벌 SVG 이름 변경
- 라이브러리 HMI SVG 이름 변경
- 라이브러리 LOGIC SVG 이름 변경
- 픽쳐 SVG 이름 변경
- 스타일 SVG 이름 변경
- 라이브러리 심볼 이름 변경

**Comment by khm34software** [comment]
더블클릭시 해당 이름이 변경되는것은 확인하였습니다.
Visual Studio의 솔루션 탐색기의 기능중 F2는 파일 이름변경, 마우스 더블클릭시 해당파일을 오픈합니다.
동일한 기능을 적용하였으면 좋겠습니다.

더블클릭으로 할 경우 원클릭과의 혼동으로 사용하기가 불편할 것 같습니다.

**Comment by BrightJoy** [comment]
javascript 엔진을 호출하는 경우에는 스레드를 이용하여 호출되어야 위와 같은 메세지가 나타나지 않습니다. 스레드를 이용하여 호출되도록 수정하였습니다.
메모리 릭 현상은 외부 엔진에서 발생현상으로 이미 발견된 현상으로 패치가 불가한 사항입니다.

**Comment by khm34software** [comment]
적용된 사항 확인하였습니다.

아래와 같이 F2를 누르고 이름 변경을 위해 마우스 좌클릭으로 범위를 지정하려고하면 범위가 지정되지 않고 객체이름이 선택되어지는 현상을 범위지정으로 변경해야될것 같습니다.
![default](https://user-images.githubusercontent.com/38027211/39222680-eeec28d8-4878-11e8-8827-a6341e0a9ef0.png)

**Comment by BrightJoy** [comment]
프로젝트 익스플로어에서 이전 선택정보와 현재선택정보가 동일하다면, 리턴 수행하도록 코드를 수정 적용하였습니다.

**Comment by khm34software** [comment]
범위 지정되는 기능 확인하였습니다.
아래와 같이 test-Task-logic_svg 항목은 F2 기능이 적용되지 않은것 같습니다.

![logic_svg](https://user-images.githubusercontent.com/38027211/39908547-86f99130-5529-11e8-93ad-1acac665e37c.png)

**Comment by khm34software** [comment]
정상동작 확인하였습니다.

**Comment by khm34software** [comment]
정상동작 확인하였습니다.
