### ISSUE TITLE
enuSpace의 *.svg 파일을 메뉴의 Save File(svg)로 저장시 Project Explorer에서 선택되어진  *.svg파일의 경로와 파일명을 가져와서 저장해야 됩니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#15]
![default](https://user-images.githubusercontent.com/38027211/38413326-4ffe6e5e-39c6-11e8-8fbb-6dc15b91fad1.png)
![1](https://user-images.githubusercontent.com/38027211/38413333-529be34e-39c6-11e8-9a9e-331fb7d4b9b9.png)
![2](https://user-images.githubusercontent.com/38027211/38413465-af8186ae-39c6-11e8-92ac-1eaf574cd061.png)

**Comment by khm34software** [comment]
[02c42a8](url)http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293

**Comment by khm34software** [comment]
http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293

**Comment by khm34software** [comment]
[](http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293)

**Comment by khm34software** [comment]
[](url)http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293

**Comment by khm34software** [comment]
[](url)02c42a8

**Comment by khm34software** [comment]
[02c42a8](url)http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293

**Comment by BrightJoy** [comment]
HOME의 Save File 메뉴에 대하여 저장로직을 현재 활성화된 뷰에 대하여 수정모드인 경우에 대해서만 활성화 되고 저장될수 있도록 연계하였습니다.

**Comment by khm34software** [comment]
수정된 해당 기능은 정상동작합니다.
다른 이름으로 저장 기능이 있어야 될것 같습니다.

**Comment by BrightJoy** [comment]
다른이름 저장하기 메뉴는 아래그림과 같이 제공됩니다.
![image](https://user-images.githubusercontent.com/29910594/38927067-8d5dd2bc-433f-11e8-8f4b-e975351751b8.png)

**Comment by khm34software** [comment]
publish or 가 들어가서 혼동됩니다. 명칭을 Save as로만 하면 좋을것 같습니다.
기존 svg의 파일이름과 파일형식을 가져와서 표현해주었으면 합니다.  (ex. test.svg 그대로 읽어와서 표시)
파일형식을 선택하는 부분에서 깨진글씨가 출력되는 에러가 표함되어 있습니다.

![default](https://user-images.githubusercontent.com/38027211/38967352-92014470-43c1-11e8-895c-16fdfaac2f19.png)

**Comment by BrightJoy** [comment]
요청된 내용을 기반으로 Save as 로직이 변경되었습니다.

**Comment by khm34software** [comment]
Picture-test.svg를 선택하고 hmi_gauge.svg를 선택한 상태에서 save as..를 누르면 파일탐색기의 파일이름이 hmi_gauge.svg로 바뀌지 않습니다.
경로도 현재 hmi_gauge.svg가 위치한 경로로 자동 지정되야 될것 같습니다.
![_](https://user-images.githubusercontent.com/38027211/39223198-9453b8c0-487b-11e8-9b4c-5ffe14685476.png)

**Comment by BrightJoy** [comment]
해당 픽처의 타입에 따라서 패스 위치를 지정하여 저장할 수 있도록 수정되었습니다.
Save as ... 이벤트 함수는 현재 활성화된 뷰를 기준으로 파일을 저장합니다.

**Comment by khm34software** [comment]
정상동작 확인하였습니다.

**Comment by khm34software** [comment]
정상동작확인하였습니다.
