### ISSUE TITLE
enuSpace의 Picture-test.svg에 컴포넌트를 끌어와서 생성후 #m_run 멤버변수에 DB변수 #@test.input1을 입력하고 엔터를 치면 에러가 간헐적으로 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#16]
![_ 1](https://user-images.githubusercontent.com/38027211/38414373-42c95a34-39c9-11e8-9a33-d9cd2a202034.png)
![_ 2](https://user-images.githubusercontent.com/38027211/38414376-45060fa4-39c9-11e8-8465-2ad6af2db881.png)
![_](https://user-images.githubusercontent.com/38027211/38414378-473e9aac-39c9-11e8-9fc3-4a2627e43927.png)

**Comment by khm34software** [comment]
http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293

**Comment by khm34software** [comment]
02c42a8

**Comment by BrightJoy** [comment]
객체의 속성 파라미터 함수 전달시 구조체 형태로 변경됨에 따라서, 발생한 현상으로 보이며 현재 패치된 버젼으로 수행시 오류가 사라졌는지 확인 검토 필요할 것으로 보입니다.

동일 이슈현황.
[issues-9](https://github.com/EXPNUNI/enuSpace-Article/issues/9)

**Comment by khm34software** [comment]
[02c42a8](url)

**Comment by khm34software** [comment]
[http://192.168.0.2/git/Repository/Commit/9b05e1d1-fff4-4354-8fa2-331ab406d7b8?commit=02c42a86108bbf66fd229fb65f46e848d51fc293](url)

**Comment by khm34software** [comment]
동일한 오류가 발생하는데 프로젝트 재 실행 후 테스트하면 증상이 발생하지 않는 경우가 많습니다.
객체의 변수값에 DB변수값 test.input2 입력후 정상동작하다가 test.input3 입력하여 재실행시 아래와 같은 에러가 발생함
![db test input2 test input3](https://user-images.githubusercontent.com/38027211/38545185-6e723b74-3ce4-11e8-994d-28b714e2673f.png)

**Comment by khm34software** [comment]
추 후 발생하면 이슈사항에 재 등록하겠습니다.
