### ISSUE TITLE
스크립트 출력창과 디버그창 출력 메세지 불일치 항목 개선이 필요할것 같습니다.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#19]
스크립트 출력창과 디버그창 출력 메세지가 불일치하는 현상이 간혈적으로 발생합니다. 디버그창에는 정상적인 오류메세지가 나타나나, 스크립창에서는 Compile OK가 나타나는 현상이 있습니다.

**Comment by shkim3445** [comment]
Error 메세지에 undefined error 를 출력하지 않던 것을 출력에러에 추가함.
				v8::String::Utf8Value str(result);
				const char* cstr = ToCString(str);
				retstr = new char[strlen(cstr) + 1];
				**_*g_error += retstr;_**
				printf("%s\n", cstr);
				sprintf_s(retstr,strlen(cstr)+1,"%s", cstr);

**Comment by BrightJoy** [comment]
![image](https://user-images.githubusercontent.com/29910594/38543717-4c57aa64-3ce0-11e8-9689-19bcc550051b.png)

스크립트의 내용이 비어 있는 경우, 컴파일 수행시 위 그림과 같이 나타납니다. 스크립트 에디터창에서도 동일한 메세지 출력이 필요할 것으로 보입니다.
