### ISSUE TITLE
chart 기능중에 시리즈의 라인 dasharray기능 추가 가능여부 검토 부탁합니다.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#20]
@lwh4525 chart에서 시리즈의 라인 속성 dasharray의 기능이 추가 가능한지 검토부탁드리며, 추가 가능하다면 연계하여 주시기 바랍니다.

**Comment by BrightJoy** [comment]
![image](https://user-images.githubusercontent.com/29910594/38601045-4b9b1a04-3da1-11e8-9fbc-65b9cc87f695.png)
차트를 생성시 자동으로 하나의 시리즈가 추가되어 있으며, data 영역에 초기값이 있는데 화면에 현시되지 않고 있습니다. 초기 생성시 화면에 현시하기 위해서는 어떻작업이 필요할까요?

@lwh4525

**Comment by lwh4525** [comment]
@BrightJoy 차트는 flow 타입을 기본으로 하여 series가 표현 되도록 변경 하였습니다. enuspace를 업데이트 해주세요.

**Comment by BrightJoy** [comment]
정상적으로 디스플레이됨을 확인하였습니다.
