### ISSUE TITLE
enuSpace의 Project Explorer-Library-Hmi-hmi_gauge.svg에서 복사한 객체를 삭제해도 hmi오브젝트 툴바에서는 삭제가 되지 않고 삭제되지 않은 객체를 드래그앤드랍시 아래와 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#22]
![_dulpicate_symbol hmi 1](https://user-images.githubusercontent.com/38027211/38544022-3553f146-3ce1-11e8-8a3c-a6fc041d6259.png)
![_dulpicate_symbol hmi](https://user-images.githubusercontent.com/38027211/38544024-380b1a54-3ce1-11e8-9001-017cb1bf7f13.png)

**Comment by BrightJoy** [comment]
객체 제거시 툴바의 정보를 업데이트 하도록 수정하였습니다.

**Comment by khm34software** [comment]
정상동작 확인하였습니다.
gauge_sector1을 복사하면 gauge_sector1_copy0, gauge_sector1_copy1, copy2, 순으로 생성되어지고
copy1, copy2를 삭제하고 다시 복사하면 copy3으로 생성됩니다. 기존의 값을 유지한채로 복사되어 copy1으로 생성되어지지 않고 있습니다.

![default](https://user-images.githubusercontent.com/38027211/39223428-0da3e03c-487d-11e8-82c4-232c620da755.png)

**Comment by BrightJoy** [comment]
불필요한 이름 작명 로직을 간소화 하고자 하는 개발자의 설계입니다.
