### ISSUE TITLE
enuSpace-js의 웹 그래픽 랜더러 연계가 되지 않습니다.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#25]
@lwh4525 enuSpace-js의 웹 그래픽 랜더러 연계가 자동으로 적용될수 있도록 보완이 필요합니다.

enuSpace for mars 버젼에서 자동으로 연계된 랜더러 버젼과 enuSpace for jupiter 버젼에서 자동으로 연계될 랜더러 버젼이 분기되어 적용이 되면 좋을것 같습니다.

**Comment by lwh4525** [comment]
@BrightJoy 이번에 분기하여 mars 버전과 jupiter버전을 나누도록 하겠습니다. 현재 웹 서버에 있는 enuspace.min 버전 파일과 mars버전에서 쓰고있는 웹 index.html 파일은 그대로 두고, 현재 작업하고 있는 랜더러파일을 합쳐 새로운 min버전 파일을 만들어 index.html파일에 연계하도록 하겠습니다.

**Comment by lwh4525** [comment]
@BrightJoy 현재 렌더러의 분기가 이루어 졌습니다. 확인 부탁드립니다.

**Comment by BrightJoy** [comment]
확인하였습니다.
