### ISSUE TITLE
enuSpace의 Labray-Hmi-hmi_gauge.svg-gauge_sector객체의 자바스크립트이벤트_ontaskview수정후 Picture-test.svg를 클릭하면 속성창 부분에서 HMI 심볼을 로드하지 못합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#26]
![labray-hmi-hmi_gauge svg-gauge_sector _ontaskview _picture-test svg hmi](https://user-images.githubusercontent.com/38027211/38601940-369d1be0-3da4-11e8-88c2-ea6adf517fcb.png)
![labray-hmi-hmi_gauge svg-gauge_sector _ontaskview _picture-test svg hmi 1](https://user-images.githubusercontent.com/38027211/38602041-87fb4e30-3da4-11e8-8438-014b5df792dd.png)

**Comment by BrightJoy** [comment]
심볼을 제작하여 픽처에서 적용후, 심볼을 재 편집하였을 경우 픽처단의 객체는 수정된 내용을 반영하지 않으며, 기존 내용을 유지하고 있습니다.

이에 명시적으로 제거후 수정된 심볼을 다시 추가하거나, F5 버튼을 클릭하여 Reload를 수행하면 수정된 심볼이 적용됩니다.

**Comment by khm34software** [comment]
현재 재현해본결과 로드가 정상적으로 됩니다.
