### ISSUE TITLE
enuSpace의 hmi_gauges.svg-gauge_sector2에서 사진1과 같이 gauge_sector 게이지와 gauge_sector1 게이지를 복사하고 gauge_sector2에 붙여넣기한다음 저장하고 복사한 gauge_sector1 게이지를 삭제하고 저장하면 1개의 게이지만 남은상태로 저장되어야 되는데 두개의 게이지가 저장된 상태로 속성창의 hmi symbol에 표현됩니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#28]
두개의 게이지 복사후 저장
![hmi](https://user-images.githubusercontent.com/38027211/38667614-d4083f6c-3e7c-11e8-89ad-3f77bf065b00.png)

복사된 한개의 게이지 삭제 후 저장
![hmi 1](https://user-images.githubusercontent.com/38027211/38667654-e7798d8a-3e7c-11e8-9f7e-292c40eb60bf.png)

**Comment by khm34software** [comment]
프로젝트 재 실행시 정상적으로 로드됩니다.
실행중에 저장시 hmisymbol을 로드해주는 부분이 추가되어야 될 것 같습니다.

**Comment by BrightJoy** [comment]
저장 버튼클릭시 해당 파일이 라이브러리 파일인 경우에는 속성창의 이미지 정보를 업데이트하는 로직을 추가하였습니다. 검토 부탁드립니다.

**Comment by khm34software** [comment]
정상 동작 확인하였습니다.
