### ISSUE TITLE
enuSapce의 Project Explorer-Library-Hmi-hmi_gauge.svg에 라이브러리저장,심볼추가,라이브러리삭제시 심볼들의 이름에 따른 순차정렬기능이 적용되어야 합니다. 

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#30]
![default](https://user-images.githubusercontent.com/38027211/38713512-812476cc-3f0c-11e8-8c76-47317f6b5f47.png)

**Comment by BrightJoy** [comment]
라이브러리에 대해서 정렬기능을 추가하였습니다. 검토바랍니다.

**Comment by khm34software** [comment]
정상확인하였습니다.

**Comment by khm34software** [comment]
정상동작 확인하였습니다.
