### ISSUE TITLE
enuSapce의 hmi_gauge.svg-gauge_cicle1심볼 생성후 속성창의 각항목의 값을 복사하고 붙여넣으면 값이 연속적으로 누적되는 현상 (svg화면 클릭시 정상 값으로 바뀜)

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#31]
값이 누적된 사진
![default](https://user-images.githubusercontent.com/38027211/38714285-626ea8c0-3f10-11e8-9e49-3c1cb1352443.png)

누적되었지만 svg화면 클릭시 정상값으로 바뀜
![1](https://user-images.githubusercontent.com/38027211/38714353-c525a3ce-3f10-11e8-96a9-336f18969d90.png)

**Comment by BrightJoy** [comment]
위 내용은 속성창의 고유기능으로 붙여넣기 수행시 해당 속성에 대하여 refresh 기능을 추가하면 되나, 다른  데이터 속성중 연속으로 붙여넣기 수행할 경우도 있을 것으로 판단되어, 마이너한 이슈사항으로 기존 기능을 유지하는 방향이 더 좋을것 같습니다.

**Comment by khm34software** [comment]
데이터 속성중 연속으로 붙여넣기 수행할 경우에 누적되어 적용되는 것이 아닌 마지막에 붙여넣기를 수행한 값이 적용되고 있습니다. (화면에 값은 누적된것처럼 표현되지만 엔터키나 마우스를 다른곳으로 클릭시 마지막에 붙여넣기한 값으로 적용됩니다) 누적되게 변경해야 되는게 아닌지 검토바랍니다.

**Comment by BrightJoy** [comment]
위 기능은 속성창의 정상적인 동작 방식입니다. 해당 속성창의 타입에 따라서, 문자열인 경우에는 누적되며 숫자형인경우에는 마지막값이 업데이트되는 현상입니다.

**Comment by khm34software** [comment]
정상 동작 확인하였습니다.
