### ISSUE TITLE
enuSpace의 우측 상단의 X표시(닫기)와 메인메뉴 EXIT로 종료시 스크린샷과 같은 런타임 에러가 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#36]
닫기 버튼으로 종료시 발생하는 에러
![x 1](https://user-images.githubusercontent.com/38027211/38923284-2a3af804-4335-11e8-93ac-84425e6b6de4.png)

![x 2](https://user-images.githubusercontent.com/38027211/38923296-2f10550e-4335-11e8-9d2d-4e366dda66f4.png)

![x 3](https://user-images.githubusercontent.com/38027211/38923579-e290f886-4335-11e8-9195-1b75db10493a.png)

메인 메뉴의 exit로 종료시 발생하는 에러
![exit](https://user-images.githubusercontent.com/38027211/38966555-d1dd3ab2-43bd-11e8-8122-43b0f5ad19d8.png)

![exit 1](https://user-images.githubusercontent.com/38027211/38966557-d512d354-43bd-11e8-8bd2-b03b26b63579.png)

![exit 2](https://user-images.githubusercontent.com/38027211/38966562-da03d278-43bd-11e8-8dc1-8499223e759d.png)

**Comment by BrightJoy** [comment]
적용된 샘플을 올려주실수 있나요? 
다른 샘플로는 재현이 불가합니다.

**Comment by khm34software** [comment]
샘플 프로젝트 파일 첨부합니다.

[test.zip](https://github.com/EXPNUNI/enuSpace-Article/files/1926470/test.zip)

**Comment by BrightJoy** [comment]
현재버젼으로 다시 테스트 부탁합니다. 재현이 안되네요.

**Comment by khm34software** [comment]
현재 사용중인 버전과 test.zip 두 버전에서 재현이 안되고 있습니다. 재 발생시 이슈에 등록하겠습니다.
