### ISSUE TITLE
enuSpace의 Hmi-hmi_gauge.svg에 Add Symbol할 경우 심볼 네임을 정하는 다이얼로그의 에디트 박스에 커서가 기본 지정되어 있게 해야됩니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#41]
![add symbol](https://user-images.githubusercontent.com/38027211/38979952-8723caa2-43f6-11e8-93df-d8c95f6e34d6.png)

![add symbol1](https://user-images.githubusercontent.com/38027211/38979956-8add1bbc-43f6-11e8-8b01-8c7ce0f1ad3e.png)

**Comment by khm34software** [comment]
기능확인 하였습니다.
아래 그림과 같이 추가 사항이 발견되었습니다.

test-Task-Add Task 에디트박스 커서 지정
![add_task](https://user-images.githubusercontent.com/38027211/39104729-9a90abb6-46ec-11e8-88ba-ed5a99da4008.png)

test-Add-New Item... 에디트박스 커서 지정
![test_add_new_item](https://user-images.githubusercontent.com/38027211/39104733-9fb56c80-46ec-11e8-8164-465c8c860b77.png)

각 항목별 Existing Item...-하위항목선택시 파일탐색기의 경로가 현재 프로젝트 경로로 지정
![default](https://user-images.githubusercontent.com/38027211/39104735-a455744c-46ec-11e8-9105-e7ddc401df9f.png)

**Comment by BrightJoy** [comment]
test-Task-Add Task 에디트박스 커서 지정
test-Add-New Item... 에디트박스 커서 지정
각 항목별 Existing Item...-하위항목선택시 파일탐색기의 경로가 현재 프로젝트 경로로 지정
보완 완료되었습니다.
