### ISSUE TITLE
enuSpace에서 추가된 데이터베이스 테그를 제거시, 데이터베이스 테그를 참조하는 객체에 대한 처리.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#5]
enuSpace에서 추가된 데이터베이스 테그를 제거시, 데이터베이스 테그를 참조하는 객체에 대한 처리가 필요. 
- HMI 심볼에 SetAttribute에 설정된 경우
- 스크립트에서 데이터베이스 태그를 이용한 경우

**Comment by khm34software** [comment]
DB변수 삭제후 재 생성후 객체에 값 입력시 정상 적용됨

**Comment by khm34software** [comment]
DB변수 삭제후 재 생성후 객체에 값 입력시 정상 적용됨
