### ISSUE TITLE
script api memcpy() 옵셋정보를 이용하는 경우에 대하여 검토가 필요합니다.

### ISSUE THREAD

**Issue by BrightJoy** [EXPNUNI/enuSpace-Article#52]
아래와 같은 스크립트를 수행할 경우, 옵셋에 따른 memcpy()함수의 검토가 필요합니다.

memcpy(&ID_CORE_MAP.data[0][0], &@OCEAN.NormalizedPower_Data[level][0][0], 15*15)

**Comment by shkim3445** [comment]
GlobalFunction 및 GlobalFunctionJS에서 Memcpy 함수 Offset및 Size 에러 검출 추가 할 때 Offset 정보를 Source 및 Destination 포인터에 추가하지 않음으로 인한 현상.
- Source 및 Destination 포인터에 Offset 더해줌.
	void* pDVal = (void*)pArrayDestPointer;
	void* pSVal = (void*)pArraySourcePointer;
->
	void* pDVal = (void*)(pArrayDestPointer + iDestOffset);
	void* pSVal = (void*)(pArraySourcePointer + iSorcOffset);

**Comment by BrightJoy** [comment]
정상동작 확인하였습니다.
