### ISSUE TITLE
enuSpace의 Open-Open File(SVG)기능을 삭제해야될것 같습니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#55]
![open_svg](https://user-images.githubusercontent.com/38027211/39914610-81edddce-5540-11e8-931e-77f4022d3d47.png)

![open_svg2](https://user-images.githubusercontent.com/38027211/39914642-97a68724-5540-11e8-9d81-b607a91b2c79.png)

Open-Open File(SVG)로 불러온 .SVG파일의 파일명을 Project Explorer에서 변경시에 해당 경로에 위치한 파일명이 변경되지 않습니다.
![open_svg3_](https://user-images.githubusercontent.com/38027211/39914645-9a3111b2-5540-11e8-85b8-a97c7a1d070e.png)

현재 적용되어있는 프로젝트 폴더 내부에서만 불러오는 기능을 사용하면 될것 같습니다.
![exist_file](https://user-images.githubusercontent.com/38027211/39915292-805d8674-5542-11e8-8e46-db7d3ada9c39.png)

**Comment by BrightJoy** [comment]
ID_FILE_OPEN 메뉴 제거 수행하였습니다.
