### ISSUE TITLE
enuSpace의 SVG를 Runtime중에 화면 임의의 곳을 여러번 클릭하면 에러 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#56]
![runtime_error](https://user-images.githubusercontent.com/38027211/39976402-825f4222-576e-11e8-82ef-4206000b5e54.png)

![runtime_error1](https://user-images.githubusercontent.com/38027211/39976404-871bb9a8-576e-11e8-9a4e-2714bf96ffc5.png)

**Comment by BrightJoy** [comment]
재현이 불가합니다.
