### ISSUE TITLE
enuSpace에서 Labrary-Hmi-Component-gauge에 입력되는 변수값이 gauge의 멤버변수 타입으로 형변환 되어 입력되지 않습니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#8]
Gauge 멤버변수 값 double m_fValue 값에 DB변수의 float값이 형변환되어 입력되지 않아서 게이지의 값이 변경 되지 않습니다.

**Comment by BrightJoy** [comment]
SetAttribute 변수에 대하여 형변환 기능 추가 및 배열변수 디스플레이 설정기능 확장 수행.

**Comment by khm34software** [comment]
DB변수 test.input3을 타입을 float 값을0.000000으로 초기화하고 게이지의 double m_fValue값에 입력하면 m_fValue값에 쓰레기값이 생성되고 게이지가 실행되지 않습니다.
![float 0 000000 double m_fvalue m_fvalue](https://user-images.githubusercontent.com/38027211/38549441-f98b268a-3cee-11e8-96b9-1f1c640c1f9a.png)

**Comment by BrightJoy** [comment]
메모리에 값을 할당하지 못하는 부분에 대하여 수정되었으며, 

다음과 같이 데이터베이스 태그 정보가 변경되었을 경우, 모든 픽쳐에 대하여 스크립트를 재등록 하여 실행하도록 수정 되었습니다.
픽쳐단에서 객체 제거된 경우에도 스크립트를 재등록 하여 실행하도록 수정 되었습니다.
@khm34software 검토 바랍니다.

**Comment by khm34software** [comment]
float 값을 double mfValue에 입력하면 값이 적용됩니다.
DB 변수에서는 소수저 이하 6자리까지 표현하지만 게이지에 출력되는 자리수는 6자리 이상입니다.
픽쳐에서 0.1씩 증가시켜주지만 실제 31.1 / 31.2 / 31.3 또는 31.100000 / 31.200000 / 31.300000 소수점 자리수 에 맞게 출력되지 않습니다.
0.1씩 증가하지 않고 소수점 이하 지정된 자리수 이외의 자리에서 값이 증가합니다.
![default](https://user-images.githubusercontent.com/38027211/38594007-41070002-3d7f-11e8-8ddf-ce8bcf0166f4.png)

**Comment by BrightJoy** [comment]
위 사항은 스크립트의 포맷을 지정하지 않았기 때문에 발생하는 현상입니다. 
lua script의 경우는 string.format("%4.2f", value)와 같이 설정하면 자리수를 적용할 수 있습니다.

@khm34software

**Comment by khm34software** [comment]
java script의 경우에서 String Format을 적용하는 방법을 알고 싶습니다.
자료를 찾아봐도 시간만 흐르고 있습니다.
var strTemp = "x";               //적용됨
strTemp("%4.2f", value);      // "%4.2f"초기값으로만 적용되고 value값이 변할때마다 strTemp의 값이 변합니다.

**Comment by khm34software** [comment]
자바스크립트에서 스트링 객체에 포맷함수를 생성하여 사용하는 법을 알고 싶습니다.
웹에서 얻은 정보로는 적용이 쉽지 않습니다.

**Comment by khm34software** [comment]
아래와 같은 방법으로 적용하였습니다.
![default](https://user-images.githubusercontent.com/38027211/38610374-9f523776-3dbb-11e8-90ff-c60b63c2727e.png)
