### ISSUE TITLE
enuSpace의 Picture-test.svg에서 객체 생성 후 그라디언트 트루로 변경 후 객체를 여러번 선택하면 예외 에러 발생합니다.

### ISSUE THREAD

**Issue by khm34software** [EXPNUNI/enuSpace-Article#9]
![4_1](https://user-images.githubusercontent.com/38027211/38410067-a0dbb528-39be-11e8-9dde-a5a070180cf4.png)

**Comment by BrightJoy** [comment]
객체의 속성 파라미터 함수 전달시 구조체 형태로 변경됨에 따라서, 발생한 현상으로 보이며 현재 패치된 버젼으로 수행시 오류가 사라졌는지 확인 검토 필요할 것으로 보입니다.

**Comment by khm34software** [comment]
현재는 발생되지 않습니다. 추 후 발생되면 이슈사항에 재 등록하겠습니다.
![default](https://user-images.githubusercontent.com/38027211/38550037-66708dca-3cf0-11e8-8aab-b786a4558e69.png)

**Comment by khm34software** [comment]
완료
